version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sandbox
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d # Mount the script directory

volumes:
  postgres-data:
