version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sandbox
    expose:
      - 5566
    ports:
      - "5566:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d # Mount the script directory

volumes:
  postgres-data:
